Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,7 +20,6 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-
     
       - name: Check input and run if true
         if: ${{ github.event.inputs.run-workflow == 'true' }}
@@ -30,10 +29,16 @@ jobs:
       - name: Check input and exit if false
         if: ${{ github.event.inputs.run-workflow == 'false' }}
         run: exit 1  # Exit the entire workflow with a non-zero code
-        
-      - name: Checkout codebase
+          
       - uses: actions/checkout@v3
       
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ env.DOCKER_USERNAME }}
+          password: ${{ env.DOCKER_PASSWORD }}
+          
+          
       - name: Build Docker image
         run: | 
           docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
@@ -43,28 +48,38 @@ jobs:
 
       # - name: Push Docker image to registry
       #   run: docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
-      - name: Run container for testing purpose
-        run: |
-          docker run -d --name ws1 -p 7050:7050 ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
-          sleep 10
-          
-      - name: display container logs
-        run: docker logs ws1
-        
+      
+      # - name: Enable Docker experimental features
+      #   run: |
+      #     echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
+      #     sudo systemctl restart docker
+
+      # - name: Install Docker Buildx
+      #   run: |
+      #     docker buildx create --use
+      #     docker buildx inspect --bootstrap
+
+      # - name: Build Docker image
+      #   run: | 
+      #     docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --file Dockerfile .
+      #     docker run -d -p 7050:7050 ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
+      #     response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:7050/health-check)
+      #     if [ "$response" -ne 200 ]; then
+      #       echo "Health check failed with status $response"
+      #       exit 1
+      #     fi
+      #     echo "Health check passed with status $response"
+      
       - name: Run container for health check 
         run: |
-          response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://127.0.0.1:7050/health-check)
+          docker run -d -p 7050:7050 ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
+          sleep 10
+          response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:7050/health-check)
           if [ "$response" -ne 200 ]; then
             echo "Health check failed with status $response"
             exit 1
           fi
           echo "Health check passed with status $response"
-          
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ env.DOCKER_USERNAME }}
-          password: ${{ env.DOCKER_PASSWORD }}
           
       - name: Push Docker image to registry
         run: docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
