Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,10 +36,15 @@ jobs:
         with:
           username: ${{ env.DOCKER_USERNAME }}
           password: ${{ env.DOCKER_PASSWORD }}
-
-      # - name: Build Docker image
-      #   run: | 
-      #     docker build -t ${{ env.DOCKER_USERNAME }}/{{ env.IMAGE_NAME }}:{{ env.IMAGE_TAG }} .
+          
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '20'
+          
+      - name: Build Docker image
+        run: | 
+          docker build -t ${{ env.DOCKER_USERNAME }}/{{ env.IMAGE_NAME }}:{{ env.IMAGE_TAG }} .
 
       # - name: Run container for health check
       #   run: docker run --rm ${{ env.DOCKER_USERNAME }}/{{ env.IMAGE_NAME }}:{{ env.IMAGE_TAG }} curl -f http://localhost:7050/health-check  # Replace PORT with your actual health check port
@@ -47,28 +52,19 @@ jobs:
       # - name: Push Docker image to registry
       #   run: docker push ${{ env.DOCKER_USERNAME }}/{{ env.IMAGE_NAME }}:{{ env.IMAGE_TAG }}
       
-      - name: Enable Docker experimental features
-        run: |
-          echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
-          sudo systemctl restart docker
-
-      - name: Install Docker Buildx
-        run: |
-          docker buildx create --use
-          docker buildx inspect --bootstrap
-
-      - name: Build Docker image
-        run: | 
-          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --file Dockerfile .
-          docker run -d -p 7050:7050 ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
-          response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:7050/health-check)
-          if [ "$response" -ne 200 ]; then
-            echo "Health check failed with status $response"
-            exit 1
-          fi
-          echo "Health check passed with status $response"
-      # - name: Run container for health check 
+      # - name: Enable Docker experimental features
       #   run: |
+      #     echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
+      #     sudo systemctl restart docker
+
+      # - name: Install Docker Buildx
+      #   run: |
+      #     docker buildx create --use
+      #     docker buildx inspect --bootstrap
+
+      # - name: Build Docker image
+      #   run: | 
+      #     docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --file Dockerfile .
       #     docker run -d -p 7050:7050 ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
       #     response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:7050/health-check)
       #     if [ "$response" -ne 200 ]; then
@@ -76,6 +72,16 @@ jobs:
       #       exit 1
       #     fi
       #     echo "Health check passed with status $response"
+      
+      - name: Run container for health check 
+        run: |
+          docker run -d -p 7050:7050 ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
+          response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:7050/health-check)
+          if [ "$response" -ne 200 ]; then
+            echo "Health check failed with status $response"
+            exit 1
+          fi
+          echo "Health check passed with status $response"
           
       - name: Push Docker image to registry
         run: docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
